name: Counts amount of Lines of Code
on: workflow_dispatch
jobs:
  counter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
      - name: Make script executable
        run: chmod +x ./scripts/count-src-lines.sh
      - name: Run script
        run: ./scripts/count-src-lines.sh


